
```{r}
library(tidyverse)
library(gt)
```


```{r}
data <- read_csv("data/final_w_sent.csv")
```


```{r}
data <- data |> 
    mutate(sentiment_d= recode_values(output,
        "MODERATELY NEGATIVE" ~ "NEGATIVE",
        "VERY NEGATIVE" ~ "NEGATIVE",
        "EXTREMELY NEGATIVE" ~ "NEGATIVE",
        "EXTREMELY POSITIVE" ~ "POSITIVE",
        "MODERATELY POSITIVE" ~ "POSITIVE"
    ))
    
```


```{r}
table_data <- data |> 
    group_by(Autor) |> 
    count(sentiment_d) |> 
    pivot_wider(names_from = sentiment_d, values_from = n,values_fill = 0) |> 
    mutate(positiv_rate = POSITIVE/(NEGATIVE + POSITIVE)) 
    

```

```{r}
plot_data <- data |> 
    group_by(Autor) |> 
    count(sentiment_d)
```


```{r}
plot <- function(Autor_plot) {
  
  plot_data |> 
    filter(Autor == Autor_plot) |>
    mutate(sentiment_d = factor(sentiment_d, 
                                levels = c("POSITIVE", "NEGATIVE"))) |>
    ggplot(aes(y = Autor, fill = sentiment_d)) +
    geom_bar(aes(x = n), stat = "identity") +
    theme_void() +
    theme(legend.position = "none") +
    scale_fill_manual(
      values = c("POSITIVE" = "#4292c6", 
                 "NEGATIVE" = "#f16913"),
      drop = FALSE
    )
}
```



```{r}
table_data |> 
    ungroup() |> 
    mutate(Sentiment_Verteilung = Autor) |> 
    arrange(desc((NEGATIVE+POSITIVE))) |> 
    gt() |>
  tab_spanner(
    label = 'Sentiments',
    columns = -Autor
  ) |> 
  cols_label(NEGATIVE = "Negativ", POSITIVE = "Positiv", positiv_rate = "Positiv in %", Sentiment_Verteilung = "Verteilung") |> 
  cols_align('left', columns = Autor) |> 
  text_transform(
    locations = cells_body(columns = 'Sentiment_Verteilung'),
    fn = function(column) {
      map(column, plot) |>
        ggplot_image(height = px(30), aspect_ratio = 5)
    }
  ) |> 
    data_color(columns = NEGATIVE, palette = "Oranges") |> 
    data_color(columns = POSITIVE, palette = "Blues") |> 
    fmt_percent(positiv_rate, decimals = 0) |> 
    gtsave("tabelle_sentiments.html")

    
```


 ```{r}
 library(webshot2)
webshot("tabelle_sentiments.html", "images/tabelle.png", zoom = 2)
 ```

 